aws_region     = "eu-central-1"
instance_type   = "t3.micro"
name_prefix     = "terraform-homework"
environment     = "dev"
course_name     = "DevOps-Terraform"
key_name        = "terraform-ec2-key"
public_key_path = "/home/selfer/.ssh/id_rsa_aws.pub"
