# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: ECS Infrastructure

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]
env:
  IMAGE_NAME: sumec
  AWS_REGION: eu-central-1
  AWS_ACCOUNT_ID: 824308980797
  TF_VERSION: 1.5.0
jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
    
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color

      - name: Terraform create ecr repository
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          TF_VAR_aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}

          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
          TF_IN_AUTOMATION: true
          TF_INPUT: false

          TF_WORKSPACE: dev
        run: |
          terraform init
          terraform plan -no-color -target=aws_ecr_repository.sumec -out=tfplan
          terraform apply -auto-approve -no-color tfplan 

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}      

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ vars.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/mynginx:{{ git.tag }}

      - name: Terraform deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ vars.AWS_REGION }}      
          TF_VAR_aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_aws_account_id: ${{ vars.AWS_ACCOUNT_ID }}
          TF_VAR_aws_region: ${{ vars.AWS_REGION }}
          TF_IN_AUTOMATION: true
          TF_INPUT: false
          TF_WORKSPACE: dev
        run: |
          terraform init
          terraform plan -no-color -out=tfplan
          terraform apply -auto-approve -no-color tfplan

      - name: Update Pull Request
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform ${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌${{ steps.fmt.outcome }}
            #### Terraform Initialization ⚙️${{ steps.init.outcome }}
            #### Terraform Validation 🤖${{ steps.validate.outcome }}
            #### Terraform Plan 📖${{ steps.plan.outcome }}
            
            <details><summary>Show Plan</summary>
            ${process.env.PLAN}
            </details>
            
            *Pushed by: @${{ github.actor }}, Action: ${{ github.event_name }}*;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      
      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -input=false
      
      - name: Get Load Balancer URL
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        id: lb_url
        run: |
          LB_URL=$(terraform output -raw load_balancer_url)
          echo "url=$LB_URL" >> $GITHUB_OUTPUT
          echo "Load Balancer URL: $LB_URL"
      
      - name: Test Application
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo "Waiting for ECS service to be stable..."
          sleep 60
          
          echo "Testing application availability..."
          for i in {1..10}; do
            if curl -f "${{ steps.lb_url.outputs.url }}"; then
              echo "Application is responding!"
              break
            else
              echo "Attempt $i failed, retrying in 30 seconds..."
              sleep 30
            fi
          done
  
